### ISSUE TITLE
Collections Datatype deprecated and removed in Python 3.10

### ISSUE THREAD

**Issue by globeone** [OzymandiasTheGreat/klembord#17]
Thanks for writing klembord, it's super useful.

###  summary
After the deprecation of the Collections datatype in Python 3.10, klembord no longer works and throws an import error.

###  documentation:
https://docs.python.org/3.9/library/collections.html
and
https://docs.python.org/3.10/library/collections.html
and
https://docs.python.org/3/library/collections.abc.html

###  Imports
On line 19 of __init_.py 
this import no longer works
from collections import OrderedDict, Mapping, ByteString, Sequence

on line 3 of winclipboard.py
from collections import OrderedDict, ByteString

and line 7 of xclipboard.py
from collections import ByteString

### Error
the error thrown is:
from collections.abc import OrderedDict, Mapping, ByteString, Sequence
ImportError: cannot import name 'OrderedDict', Mapping, ByteString from 'collections.abc'

### Request
any chance to fix this for python3.10?

**Comment by globeone** [comment]
@OzymandiasTheGreat 
I tried to fix it myself in a fork  globeone/klembord, please see if these changes are valid, polish and commit to the original when helpful.

**Comment by OzymandiasTheGreat** [comment]
Thanks for bringing this to my attention, I don't use python much these days, so I completely missed the deprecation notice.
Just pushed out a version with updated imports, everything should work again.

**Comment by globeone** [comment]
@OzymandiasTheGreat 
Thanks for revisiting this code.

### Summary
Unfortunately, the 0.3.0 code is still missing a ".abc" in the import of Mapping. 

for Python3.10
`from collections.abc import Mapping, MutableMapping` 

### Documentation
Collections.abc now has the Mapping and MutableMapping functions
https://docs.python.org/3/library/collections.abc.html

### Quicklink to Mapping
https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping

### Quicklink to MutableMapping
https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableMapping

### Error when running klembord 0.3.0
```
line 7, in <module>
    from collections import Mapping,MutableMapping
ImportError: cannot import name 'Mapping' from 'collections'
```

**Comment by OzymandiasTheGreat** [comment]
~~Missed one I guess, did run fine on python 3.10.1 on my Ubuntu box. Will fix before the end of the day.~~
Just double checked. Mapping is only imported in `__init__.py` and it's the correct `.abc` import.
Also checked to make sure the correct code is pushed to pypi. You may be having a caching issue or version conflict.

**Comment by globeone** [comment]
Thanks, I'll uninstall Python and reinstall it to see if it makes a difference.

**Comment by globeone** [comment]
@OzymandiasTheGreat 
You were absolutely right, after clearing the cache and uninstalling python3.9 (apparently both 3.9 and 3.10 were installed) and removing __pycache__ from my project klembord is now working perfectly in 3.10. Thanks for the quick support 🥇 and have a happy and healthy new year.
